app:
  version: ${project.version}
#${project.version}



mybatis-plus:
  type-enums-package: group.yzhs.alarm.constant
  configuration:
    # 3.0.8之前版本问题默认将枚举注册为EnumOrdinalTypeHandler,这是错误的方式,默认是 org.apache.ibatis.type.EnumTypeHandler
    # 如果项目之中实体统一使用IEnum或注解的方式,可配置成 com.baomidou.mybatisplus.extension.handlers.EnumTypeHandler,也可省略上面的type-enums-package配置
    # 配置type-enums-package只对注解方式的枚举处理能提前加载缓存. com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    default-enum-type-handler:  org.apache.ibatis.type.EnumOrdinalTypeHandler
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted

#logging:
#  level:
#    com.baomidou.mybatisplus.samples: debug