spring:
  application:
    name: alarm
  profiles:
    active: prod

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dcsalarm?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      max-active: 20
      min-idle: 1
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      validation-query: select 'x'
      filters: stat,wall,slf4j,config
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        session-stat-enable: false
        session-stat-max-count: 1000
        principal-cookie-name: admin
        principal-session-name: admin
        profile-enable: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin
        allow:
        deny:

  servlet:
    multipart:
      enabled: true
      max-request-size: 100MB
      max-file-size: 100MB


server:
  port: 8090
  servlet:
    session:
      timeout: 60s

rules:
  filelocation: E:\\project\\2021_Project\\alarm\\config\\Production_Line.xml

alarm-history-archive: true
alarm-history-execute-period: 8748000000


collector:
  dataresurce: iot
  innerurl: http://127.0.0.1:8770
  ioturl: http://127.0.0.1/iot
wx:
  url: http://127.0.0.1:5555/SendMsgAction
  department: 江西鹰鹏DCS自动推送群
  #发生报警后，在这时间段内不进行报警/推送
  pushIntervalSec: 600
  # 持续报警状态一段时间，就报警/推送一次
  continueAlarmSec: 600

audio:
# 0-5数字越大语音越快
  rate: 1






