spring:
  application:
    name: alarm
  profiles:
    active: prod

server:
  port: 8090
  servlet:
    session:
      timeout: 60s

rules:
  filelocation: E:\\project\\2021_Project\\alarm\\config\\Production_Line.xml

alarm-history-archive: true
alarm-history-execute-period: 8748000000


collector:
  dataresurce: iot
  innerurl: http://127.0.0.1:8770
  ioturl: http://127.0.0.1/iot
wx:
  url: http://127.0.0.1:5555/SendMsgAction
  department: 江西鹰鹏DCS自动推送群
  #发生报警后，在这时间段内不进行报警/推送
  pushIntervalSec: 600
  # 持续报警状态一段时间，就报警/推送一次
  continueAlarmSec: 600

audio:
# 0-5数字越大语音越快
  rate: 1






